#!/usr/bin/env python3
"""Generate shell completions for mos from the CLI source of truth.

Why this exists: the bash/zsh/fish completion scripts must list every
subcommand and tray action. Hand-maintaining those lists is exactly the
drift the repo gates everywhere else (schemas/check_readme.py, the
amalgamate --check gate). So the *data* is extracted from the one place
that already decides it — the CLI dispatch — and the completion files are
generated, never edited by hand.

Sources of truth (a new verb/action/flag is picked up with no edit here):
  - subcommands   : cli/main.c     strcmp(cmd, "<verb>")        dispatch
  - tray actions  : cli/tray.c     strcmp(opt_tray_action, "<action>")
  - long options  : cli/main.c     long_options[] table
  - descriptions  : cli/main.c     the "Subcommands:" help block (best-effort,
                    falls back to the bare verb when a line can't be parsed)

The verb-scoped flag partition (--force/--persistent belong to tray,
--dump to probe) mirrors main.c's own validation guards and is the one
structural rule kept in this script; short-option pairings (-i/-j/-h) are
likewise structural. Everything that GROWS when a command is added — the
verb list, the action list — is derived.

Usage:
  gen-completions.py            regenerate completions/{mos.bash,_mos,mos.fish}
  gen-completions.py --check    regenerate in memory and diff against the
                                committed files; exit 1 on any drift
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN_C = os.path.join(ROOT, "cli", "main.c")
TRAY_C = os.path.join(ROOT, "cli", "tray.c")
OUT_DIR = os.path.join(ROOT, "completions")

GENERATED_NOTE = (
    "GENERATED by scripts/gen-completions.py from the CLI dispatch "
    "(cli/main.c, cli/tray.c).\nDo not edit by hand: run "
    "`python3 scripts/gen-completions.py` (or `make completions`) and commit.\n"
    "The verb and action lists are derived, so adding a command needs no edit "
    "here."
)

# Flags scoped to a single verb (mirrors main.c's validation guards:
# `(flag_force||flag_persistent) && !flag_tray` and `flag_dump && !flag_probe`).
TRAY_FLAGS = ["--force", "--persistent"]
PROBE_FLAGS = ["--dump"]


def read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def extract_subcommands(main_c):
    """Verb names, in dispatch order, from the strcmp(cmd, "...") chain."""
    verbs = re.findall(r'strcmp\(cmd,\s*"([a-z]+)"\)', main_c)
    # Dedup preserving order (each verb appears once, but be defensive).
    seen, out = set(), []
    for v in verbs:
        if v not in seen:
            seen.add(v)
            out.append(v)
    if not out:
        sys.exit("gen-completions: no subcommands found in cli/main.c")
    return out


def extract_tray_actions(tray_c):
    actions = re.findall(r'strcmp\(opt_tray_action,\s*"([a-z]+)"\)', tray_c)
    seen, out = set(), []
    for a in actions:
        if a not in seen:
            seen.add(a)
            out.append(a)
    if not out:
        sys.exit("gen-completions: no tray actions found in cli/tray.c")
    return out


def extract_long_options(main_c):
    """Long-option names from the long_options[] table."""
    block = re.search(r"long_options\[\]\s*=\s*\{(.*?)\n\};", main_c, re.S)
    if not block:
        sys.exit("gen-completions: long_options[] table not found in cli/main.c")
    return re.findall(r'\{\s*"([a-z]+)"', block.group(1))


def extract_descriptions(main_c, verbs):
    """Short, clean descriptions from the help 'Subcommands:' block.

    Best-effort: the help text is C string literals with \\n line breaks and
    column-aligned wrapping. We join the literals, walk the lines under
    'Subcommands:', and take the first phrase of each verb's description
    (cutting at ' — ', ' (', or '.'), sanitized to a shell/zsh/fish-safe set.
    A verb we can't parse falls back to its own name — completions still work.
    """
    # Reconstruct the printed help text from the fprintf string literals.
    lits = re.findall(r'"((?:[^"\\]|\\.)*)"', main_c)
    text = "".join(lits)
    text = text.replace("\\n", "\n").replace('\\"', '"').replace("\\t", "\t")

    lines = text.split("\n")
    # Window: from the "Subcommands:" header to the blank line before "Drive".
    try:
        start = next(i for i, l in enumerate(lines) if l.strip() == "Subcommands:")
    except StopIteration:
        return {v: v for v in verbs}

    descs = {}
    verb_re = re.compile(r"^  (" + "|".join(map(re.escape, verbs)) + r")\b(.*)$")
    i = start + 1
    cur = None
    buf = []
    while i < len(lines):
        line = lines[i].rstrip()
        if not line.strip():
            break  # end of the subcommands block
        m = verb_re.match(line)
        if m:
            if cur is not None:
                descs[cur] = " ".join(buf).strip()
            cur = m.group(1)
            # Strip placeholder tokens ([drive], <action>, <drive>) off the tail.
            tail = re.sub(r"[\[<][a-z]+[\]>]", "", m.group(2)).strip()
            buf = [tail] if tail else []
        elif cur is not None:
            buf.append(line.strip())
        i += 1
    if cur is not None:
        descs[cur] = " ".join(buf).strip()

    out = {}
    for v in verbs:
        d = descs.get(v, "").strip()
        # First phrase only: cut at the EARLIEST of a colon, em-dash, open
        # paren, or period (the help lines use ':' for the verbs whose
        # description leads with a label — "Control the tray:", "Diagnostic:").
        cuts = [d.find(sep) for sep in (":", " — ", " (", ".")]
        cuts = [i for i in cuts if i > 0]
        if cuts:
            d = d[:min(cuts)]
        d = re.sub(r"\s+", " ", d).strip()
        # Keep a conservative, quote/colon/backtick-free character set so the
        # string is safe in zsh 'tag:desc' and fish -d 'desc' contexts.
        d = re.sub(r"[^A-Za-z0-9 /+\-]", "", d).strip()
        out[v] = d if d else v
    return out


def comment_block(prefix):
    return "\n".join(prefix + line if line else prefix.rstrip()
                     for line in GENERATED_NOTE.split("\n"))


def gen_bash(verbs, actions, long_opts):
    globals_ = ["-i", "--index", "--bsd", "-j", "--json", "-h", "--help",
                "--version"]
    # Sanity: every global long opt we list must exist in the table.
    for name in ("index", "bsd", "json", "help", "version"):
        if name not in long_opts:
            sys.exit(f"gen-completions: expected long option --{name} missing")
    sub = " ".join(verbs)
    g = " ".join(globals_)
    acts = " ".join(actions)
    tray = g + " " + " ".join(TRAY_FLAGS)
    probe = g + " " + " ".join(PROBE_FLAGS)
    return f"""{comment_block('# ')}

_mos()
{{
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n : || return
    else
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        prev="${{COMP_WORDS[COMP_CWORD-1]}}"
        words=("${{COMP_WORDS[@]}}")
        cword=$COMP_CWORD
    fi

    local subcommands="{sub}"
    local global_opts="{g}"

    case "$prev" in
        -i|--index) return ;;
        --bsd) COMPREPLY=( $(compgen -W "disk" -- "$cur") ); return ;;
    esac

    local i sub="" subidx=0
    for ((i=1; i < cword; i++)); do
        case "${{words[i]}}" in
            -*) ;;
            *) sub="${{words[i]}}"; subidx=$i; break ;;
        esac
    done

    if [[ -z "$sub" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
        fi
        return
    fi

    if [[ "$sub" == "tray" && $cword -eq $((subidx + 1)) && "$cur" != -* ]]; then
        COMPREPLY=( $(compgen -W "{acts}" -- "$cur") )
        return
    fi

    local opts="$global_opts"
    case "$sub" in
        tray)  opts="{tray}" ;;
        probe) opts="{probe}" ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    fi
}}
complete -F _mos mos
"""


def gen_zsh(verbs, actions, descs):
    sub_lines = "\n".join(
        f"                '{v}:{descs[v]}'" for v in verbs
    )
    act = " ".join(actions)
    # tray and probe get a dedicated _arguments call; everything else falls
    # through to the global options. Generated from the verb list so a new
    # verb is covered by the default branch automatically.
    return f"""#compdef mos
{comment_block('# ')}

_mos() {{
    local curcontext="$curcontext" state line
    typeset -A opt_args

    local -a global_opts
    global_opts=(
        '(-i --index)'{{-i,--index}}'[1-based drive index]:index:'
        '--bsd[BSD form selector]:bsd name:_files -g "disk*" -W /dev'
        '(-j --json)'{{-j,--json}}'[emit JSON output]'
        '(-h --help)'{{-h,--help}}'[show help]'
        '--version[show version]'
    )

    _arguments -C \\
        "${{global_opts[@]}}" \\
        '1: :->subcmd' \\
        '*:: :->args' && return

    case $state in
        subcmd)
            local -a subcommands
            subcommands=(
{sub_lines}
            )
            _describe -t commands 'mos subcommand' subcommands
            ;;
        args)
            case $line[1] in
                tray)
                    _arguments \\
                        "${{global_opts[@]}}" \\
                        '--force[tray eject: ALLOW (unlock) before ejecting]' \\
                        '--persistent[tray lock/unlock: Persistent Prevent state]' \\
                        '1:action:({act})'
                    ;;
                probe)
                    _arguments \\
                        "${{global_opts[@]}}" \\
                        '--dump[one-shot DiscRecording dictionary capture]'
                    ;;
                *)
                    _arguments "${{global_opts[@]}}"
                    ;;
            esac
            ;;
    esac
}}

_mos "$@"
"""


def gen_fish(verbs, actions, descs):
    verb_alt = " ".join(verbs)
    sub_lines = "\n".join(
        f"complete -c mos -f -n __fish_mos_no_subcommand -a {v} "
        f"-d '{descs[v]}'" for v in verbs
    )
    act = " ".join(actions)
    return f"""{comment_block('# ')}

# A subcommand has been given when one of the verbs appears in the tokens.
function __fish_mos_no_subcommand
    set -l cmd (commandline -opc)
    if test (count $cmd) -eq 1
        return 0
    end
    for word in $cmd[2..-1]
        switch $word
            case {verb_alt}
                return 1
        end
    end
    return 0
end

function __fish_mos_using_subcommand
    set -l cmd (commandline -opc)
    for word in $cmd[2..-1]
        switch $word
            case {verb_alt}
                test "$word" = "$argv[1]"
                return
        end
    end
    return 1
end

# Subcommands (only before one is chosen).
{sub_lines}

# tray actions (only right after `tray`).
complete -c mos -f -n '__fish_mos_using_subcommand tray' -a '{act}' -d 'tray action'

# Global options.
complete -c mos -s i -l index   -d '1-based drive index' -x
complete -c mos      -l bsd     -d 'BSD form selector' -x
complete -c mos -s j -l json    -d 'Emit JSON output'
complete -c mos -s h -l help    -d 'Show help'
complete -c mos      -l version -d 'Show version'

# Subcommand-scoped options.
complete -c mos -l force      -n '__fish_mos_using_subcommand tray'  -d 'eject: ALLOW (unlock) first'
complete -c mos -l persistent -n '__fish_mos_using_subcommand tray'  -d 'lock/unlock: Persistent Prevent'
complete -c mos -l dump       -n '__fish_mos_using_subcommand probe' -d 'One-shot DiscRecording capture'
"""


def build():
    main_c = read(MAIN_C)
    tray_c = read(TRAY_C)
    verbs = extract_subcommands(main_c)
    actions = extract_tray_actions(tray_c)
    long_opts = extract_long_options(main_c)
    descs = extract_descriptions(main_c, verbs)
    return {
        "mos.bash": gen_bash(verbs, actions, long_opts),
        "_mos": gen_zsh(verbs, actions, descs),
        "mos.fish": gen_fish(verbs, actions, descs),
    }


def main(argv):
    check = "--check" in argv[1:]
    files = build()
    drift = False
    for name, content in files.items():
        path = os.path.join(OUT_DIR, name)
        if check:
            try:
                current = read(path)
            except FileNotFoundError:
                current = None
            if current != content:
                drift = True
                print(f"gen-completions: DRIFT in completions/{name}")
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"gen-completions: wrote completions/{name}")
    if check and drift:
        print("\ncompletions/ is stale against the CLI. Run "
              "`python3 scripts/gen-completions.py` and commit.")
        return 1
    if check:
        print("OK: completions/ matches the CLI dispatch")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
