#!/usr/bin/env python3
"""Generate the mos CLI docs (shell completions + man SUBCOMMANDS) from source.

Why this exists: the bash/zsh/fish completions and the man page's per-command
list must name every subcommand and tray action. Hand-maintaining those is
exactly the drift the repo gates everywhere else (schemas/check_readme.py, the
amalgamate --check gate). So the *data* is extracted from the one place that
already decides it — the command table — and these files are generated, never
edited by hand. `mos --help` reads the same table at runtime, so help,
completions, and the man page show one text from one source.

Sources of truth (a new verb/action/flag is picked up with no edit here):
  - subcommands   : cli/main.c     the &mos_cli_command_<verb> table array
  - tray actions  : cli/tray.c     strcmp(opt_tray_action, "<action>")
  - long options  : cli/main.c     long_options[] table
  - per-command   : cli/<verb>.c   each command's descriptor .summary and
                    .synopsis fields — the SAME text `mos --help` prints.
                    Falls back to the bare verb if a descriptor is unparsable.

What is generated:
  - completions/{mos.bash,_mos,mos.fish}  (full files)
  - the SUBCOMMANDS block of man/mos.1, between the BEGIN/END markers (the
    rest of the man page — global reference: OPTIONS, EXAMPLES, … — is
    hand-written and untouched).

The verb-scoped flag partition (--force belongs to tray,
--dump to probe) mirrors main.c's own validation guards and is the one
structural rule kept in this script; short-option pairings (-i/-j/-h) are
likewise structural. Everything that GROWS when a command is added — the
verb list, the action list — is derived.

Usage:
  gen-cli-docs.py            regenerate the completions + man SUBCOMMANDS block
  gen-cli-docs.py --check    regenerate in memory and diff against the
                                committed files; exit 1 on any drift
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN_C = os.path.join(ROOT, "cli", "main.c")
TRAY_C = os.path.join(ROOT, "cli", "tray.c")
OUT_DIR = os.path.join(ROOT, "completions")
MAN_PATH = os.path.join(ROOT, "man", "mos.1")

# The generated SUBCOMMANDS region of man/mos.1 lives between these roff-comment
# markers; everything outside them is hand-written and left untouched.
MAN_BEGIN = '.\\" BEGIN GENERATED SUBCOMMANDS — gen-cli-docs.py (edit cli/<verb>.c descriptors)'
MAN_END = '.\\" END GENERATED SUBCOMMANDS'

GENERATED_NOTE = (
    "GENERATED by scripts/gen-cli-docs.py from the CLI command table "
    "(the &mos_cli_command_* array in cli/main.c, each cli/<verb>.c "
    "descriptor, cli/tray.c actions).\nDo not edit by hand: run "
    "`python3 scripts/gen-cli-docs.py` (or `make cli-docs`) and commit.\n"
    "The verb and action lists are derived, so adding a command needs no edit "
    "here."
)

# Flags scoped to a single verb (mirrors main.c's validation guards:
# `flag_force && !flag_tray` and `flag_dump && !flag_probe`).
TRAY_FLAGS = ["--force"]
PROBE_FLAGS = ["--dump", "--capture"]


def read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def extract_subcommands(main_c):
    """Verb names, in dispatch order, from main.c's command-table array
    (the &mos_cli_command_<verb> entries)."""
    verbs = re.findall(r'&mos_cli_command_([a-z]+)\b', main_c)
    # Dedup preserving order (each verb appears once, but be defensive).
    seen, out = set(), []
    for v in verbs:
        if v not in seen:
            seen.add(v)
            out.append(v)
    if not out:
        sys.exit("gen-cli-docs: no subcommands found in cli/main.c")
    return out


def extract_tray_actions(tray_c):
    actions = re.findall(r'strcmp\(opt_tray_action,\s*"([a-z]+)"\)', tray_c)
    seen, out = set(), []
    for a in actions:
        if a not in seen:
            seen.add(a)
            out.append(a)
    if not out:
        sys.exit("gen-cli-docs: no tray actions found in cli/tray.c")
    return out


def extract_long_options(main_c):
    """Long-option names from the long_options[] table."""
    block = re.search(r"long_options\[\]\s*=\s*\{(.*?)\n\};", main_c, re.S)
    if not block:
        sys.exit("gen-cli-docs: long_options[] table not found in cli/main.c")
    return re.findall(r'\{\s*"([a-z]+)"', block.group(1))


def descriptor_field(verb, field):
    """Raw value of a descriptor field (.summary, .synopsis) from cli/<verb>.c —
    C-unescaped and whitespace-collapsed; "" if the file or field is absent."""
    path = os.path.join(ROOT, "cli", verb + ".c")
    try:
        src = read(path)
    except FileNotFoundError:
        return ""
    m = re.search(r"mos_cli_command_" + re.escape(verb) + r"\s*=\s*\{(.*?)\};",
                  src, re.S)
    block = m.group(1) if m else src
    fm = re.search(r'\.' + field + r'\s*=\s*"((?:[^"\\]|\\.)*)"', block)
    if not fm:
        return ""
    return re.sub(r"\s+", " ", fm.group(1).replace('\\"', '"')).strip()


def extract_descriptions(verbs):
    """Completion-menu text per verb: each descriptor's .summary, stripped of
    characters unsafe in the zsh 'tag:desc' / fish -d 'desc' contexts (quotes,
    backticks, colons). Bare verb when absent. Same source as `mos --help` and
    the man page — only the per-context rendering differs."""
    out = {}
    for v in verbs:
        d = re.sub(r"[`'\":]", "", descriptor_field(v, "summary")).strip()
        out[v] = d if d else v
    return out


def extract_man_summaries(verbs):
    """Per-verb summary for the man page. roff body text permits parens/colons,
    so no character stripping — just the raw descriptor .summary (bare verb if
    absent)."""
    return {v: (descriptor_field(v, "summary") or v) for v in verbs}


def extract_synopses(verbs):
    """Per-verb .synopsis ('[drive]', '<action> [drive]', '')."""
    return {v: descriptor_field(v, "synopsis") for v in verbs}


def comment_block(prefix):
    return "\n".join(prefix + line if line else prefix.rstrip()
                     for line in GENERATED_NOTE.split("\n"))


def gen_bash(verbs, actions, long_opts):
    globals_ = ["-i", "--index", "--bsd", "--registry", "-j", "--json", "-h",
                "--help", "--version"]
    # Sanity: every global long opt we list must exist in the table.
    for name in ("index", "bsd", "registry", "json", "help", "version"):
        if name not in long_opts:
            sys.exit(f"gen-cli-docs: expected long option --{name} missing")
    sub = " ".join(verbs)
    g = " ".join(globals_)
    acts = " ".join(actions)
    return f"""{comment_block('# ')}
{BASH_DRIVES_HELPER}
_mos()
{{
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n : || return
    else
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        prev="${{COMP_WORDS[COMP_CWORD-1]}}"
        words=("${{COMP_WORDS[@]}}")
        cword=$COMP_CWORD
    fi

    local subcommands="{sub}"
    local global_opts="{g}"

    case "$prev" in
        -i|--index|--registry) return ;;
        --bsd) _mos_drives; return ;;
    esac

    local i sub="" subidx=0
    for ((i=1; i < cword; i++)); do
        case "${{words[i]}}" in
            -*) ;;
            *) sub="${{words[i]}}"; subidx=$i; break ;;
        esac
    done

    if [[ -z "$sub" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
            _mos_drives
        fi
        return
    fi

    if [[ "$sub" == "tray" && $cword -eq $((subidx + 1)) && "$cur" != -* ]]; then
        COMPREPLY=( $(compgen -W "{acts}" -- "$cur") )
        return
    fi

    local opts="$global_opts"
    case "$sub" in
        tray)
            local tray_act="" j
            for ((j=subidx+1; j < cword; j++)); do
                case "${{words[j]}}" in -*) ;; *) tray_act="${{words[j]}}"; break ;; esac
            done
            [[ -z "$tray_act" || "$tray_act" == "eject" ]] && opts="$opts --force"
            ;;
        probe) opts="$opts --dump --capture" ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    fi
}}
complete -F _mos mos
"""


ZSH_DRIVES_HELPER = r"""
# Query attached optical drives from `mos list --json`. Produces completions of
# the form "/dev/disk4:ready LG BD-RE WH16NS60" — bsd_node as the completion
# value, drive state + identity as the description.
# Requires jq; silently yields no candidates when jq is absent (mos itself
# has no runtime dependencies, so jq is never assumed to be present).
_mos_drives() {
  (( $+commands[jq] )) || return
  local -a drives
  drives=(${(f)"$(mos list --json 2>/dev/null | jq -r '.drives[]|"\(.bsd_node):\(.state) \(.vendor) \(.product)"' 2>/dev/null)"})
  _describe 'drives' drives
}
"""

BASH_DRIVES_HELPER = r"""
# Query attached optical drives from `mos list --json`. Appends BSD-node paths
# to COMPREPLY. Requires jq; no-op when absent (mos itself has no runtime deps).
_mos_drives()
{
    command -v jq >/dev/null 2>&1 || return
    local drives
    drives=$(mos list --json 2>/dev/null | jq -r '.drives[].bsd_node' 2>/dev/null)
    [[ -n "$drives" ]] && COMPREPLY+=( $(compgen -W "$drives" -- "$cur") )
}
"""

FISH_DRIVES_HELPER = r"""
# Query attached optical drives from `mos list --json`. Each line is
# "bsd_node<TAB>state vendor product" for fish's description display.
# Requires jq; no-op when absent (mos itself has no runtime deps).
function __fish_mos_list_drives
    type -q jq; or return
    mos list --json 2>/dev/null | jq -r '.drives[]|"\(.bsd_node)\t\(.state) \(.vendor) \(.product)"' 2>/dev/null
end
"""

FISH_TRAY_EJECT_GUARD = r"""
# True when the current mos invocation has 'tray eject' as its action context.
# Used to gate --force to the eject action only.
function __fish_mos_tray_eject
    set -l cmd (commandline -opc)
    set -l found_tray 0
    for word in $cmd[2..-1]
        if test $found_tray -eq 1
            test "$word" = "eject"
            return
        end
        if test "$word" = "tray"
            set found_tray 1
        end
    end
    return 1
end
"""


def gen_zsh(verbs, actions, descs):
    sub_lines = "\n".join(
        f"                '{v}:{descs[v]}'" for v in verbs
    )
    act = " ".join(actions)
    # tray and probe get a dedicated _arguments call; everything else falls
    # through to the global options. Generated from the verb list so a new
    # verb is covered by the default branch automatically.
    #
    # _mos_drives is called alongside _describe in the subcmd state so the
    # first positional completes both verb names and live drive BSD nodes.
    # --bsd uses it directly instead of the generic _files glob.
    return f"""#compdef mos
{comment_block('# ')}
{ZSH_DRIVES_HELPER}
_mos() {{
    local curcontext="$curcontext" state line
    typeset -A opt_args

    local -a global_opts
    global_opts=(
        '(-i --index)'{{-i,--index}}'[1-based drive index]:index:'
        '--bsd[BSD form selector]:bsd name:_mos_drives'
        '--registry[registry_id selector]:registry id:'
        '(-j --json)'{{-j,--json}}'[emit JSON output]'
        '(-h --help)'{{-h,--help}}'[show help]'
        '--version[show version]'
    )

    _arguments -C \\
        "${{global_opts[@]}}" \\
        '1: :->subcmd' \\
        '*:: :->args' && return

    case $state in
        subcmd)
            local -a subcommands
            subcommands=(
{sub_lines}
            )
            _describe -t commands 'mos subcommand' subcommands
            _mos_drives
            ;;
        args)
            case $line[1] in
                tray)
                    local -a tray_opts
                    tray_opts=("${{global_opts[@]}}")
                    local _tray_act
                    for w in "${{(@)line[2,-1]}}"; do [[ $w != -* ]] && {{ _tray_act=$w; break; }}; done
                    [[ -z $_tray_act || $_tray_act == eject ]] && \\
                        tray_opts+=('--force[tray eject: also clear a tray Prevent lock (never forces the filesystem)]')
                    _arguments \\
                        "${{tray_opts[@]}}" \\
                        '1:action:({act})'
                    ;;
                probe)
                    _arguments \\
                        "${{global_opts[@]}}" \\
                        '--dump[one-shot DiscRecording dictionary capture]' \\
                        '--capture[fixed-menu raw MMC capture (mos.capture.v0)]'
                    ;;
                *)
                    _arguments "${{global_opts[@]}}"
                    ;;
            esac
            ;;
    esac
}}

_mos "$@"
"""


def gen_fish(verbs, actions, descs):
    verb_alt = " ".join(verbs)
    sub_lines = "\n".join(
        f"complete -c mos -f -n __fish_mos_no_subcommand -a {v} "
        f"-d '{descs[v]}'" for v in verbs
    )
    act = " ".join(actions)
    return f"""{comment_block('# ')}

# A subcommand has been given when one of the verbs appears in the tokens.
function __fish_mos_no_subcommand
    set -l cmd (commandline -opc)
    if test (count $cmd) -eq 1
        return 0
    end
    for word in $cmd[2..-1]
        switch $word
            case {verb_alt}
                return 1
        end
    end
    return 0
end

function __fish_mos_using_subcommand
    set -l cmd (commandline -opc)
    for word in $cmd[2..-1]
        switch $word
            case {verb_alt}
                test "$word" = "$argv[1]"
                return
        end
    end
    return 1
end
{FISH_DRIVES_HELPER}
{FISH_TRAY_EJECT_GUARD}
# Subcommands (only before one is chosen).
{sub_lines}
complete -c mos -f -n __fish_mos_no_subcommand -a '(__fish_mos_list_drives)'

# tray actions (only right after `tray`).
complete -c mos -f -n '__fish_mos_using_subcommand tray' -a '{act}' -d 'tray action'

# Global options.
complete -c mos -s i -l index   -d '1-based drive index' -x
complete -c mos      -l bsd     -d 'BSD form selector' -a '(__fish_mos_list_drives)' -x
complete -c mos      -l registry -d 'registry_id selector' -x
complete -c mos -s j -l json    -d 'Emit JSON output'
complete -c mos -s h -l help    -d 'Show help'
complete -c mos      -l version -d 'Show version'

# Subcommand-scoped options.
complete -c mos -l force      -n __fish_mos_tray_eject  -d 'eject: also clear a tray Prevent lock (never forces the filesystem)'
complete -c mos -l dump       -n '__fish_mos_using_subcommand probe' -d 'One-shot DiscRecording capture'
complete -c mos -l capture    -n '__fish_mos_using_subcommand probe' -d 'Fixed-menu raw MMC capture'
"""


def man_subcommands_block(verbs, summaries, synopses):
    """The roff text for the man SUBCOMMANDS region (markers inclusive): one
    .TP entry per command — bold name, roman synopsis, summary on the next
    line."""
    lines = [MAN_BEGIN]
    for v in verbs:
        syn = synopses.get(v, "")
        lines.append(".TP")
        lines.append('.BR %s " %s"' % (v, syn) if syn else ".B %s" % v)
        lines.append(summaries[v])
    lines.append(MAN_END)
    return "\n".join(lines) + "\n"


def splice_man(man_text, block):
    """Replace the marked SUBCOMMANDS region of man/mos.1 with block (the rest
    of the file is hand-written and preserved verbatim)."""
    bi = man_text.find(MAN_BEGIN)
    ei = man_text.find(MAN_END)
    if bi < 0 or ei < 0:
        sys.exit("gen-cli-docs: man/mos.1 is missing the SUBCOMMANDS markers "
                 "(expected the BEGIN/END GENERATED SUBCOMMANDS roff comments)")
    line_start = man_text.rfind("\n", 0, bi) + 1      # start of the BEGIN line
    after = man_text.find("\n", ei)
    line_end = len(man_text) if after < 0 else after + 1  # past the END line
    return man_text[:line_start] + block + man_text[line_end:]


def build():
    """Map of absolute-path -> full file content for every generated artifact."""
    main_c = read(MAIN_C)
    tray_c = read(TRAY_C)
    verbs = extract_subcommands(main_c)
    actions = extract_tray_actions(tray_c)
    long_opts = extract_long_options(main_c)
    descs = extract_descriptions(verbs)
    out = {
        os.path.join(OUT_DIR, "mos.bash"): gen_bash(verbs, actions, long_opts),
        os.path.join(OUT_DIR, "_mos"):     gen_zsh(verbs, actions, descs),
        os.path.join(OUT_DIR, "mos.fish"): gen_fish(verbs, actions, descs),
    }
    block = man_subcommands_block(verbs, extract_man_summaries(verbs),
                                  extract_synopses(verbs))
    out[MAN_PATH] = splice_man(read(MAN_PATH), block)
    return out


def main(argv):
    check = "--check" in argv[1:]
    outputs = build()
    drift = False
    for path, content in outputs.items():
        rel = os.path.relpath(path, ROOT)
        if check:
            try:
                current = read(path)
            except FileNotFoundError:
                current = None
            if current != content:
                drift = True
                print(f"gen-cli-docs: DRIFT in {rel}")
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"gen-cli-docs: wrote {rel}")
    if check and drift:
        print("\nCLI docs are stale against the command table. Run "
              "`python3 scripts/gen-cli-docs.py` and commit.")
        return 1
    if check:
        print("OK: CLI docs match the command table")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
