# GENERATED by scripts/gen-completions.py from the CLI dispatch (cli/main.c, cli/tray.c).
# Do not edit by hand: run `python3 scripts/gen-completions.py` (or `make completions`) and commit.
# The verb and action lists are derived, so adding a command needs no edit here.

_mos()
{
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n : || return
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

    local subcommands="state list watch metadata drive features tray capacity probe"
    local global_opts="-i --index --bsd -j --json -h --help --version"

    case "$prev" in
        -i|--index) return ;;
        --bsd) COMPREPLY=( $(compgen -W "disk" -- "$cur") ); return ;;
    esac

    local i sub="" subidx=0
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            -*) ;;
            *) sub="${words[i]}"; subidx=$i; break ;;
        esac
    done

    if [[ -z "$sub" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
        fi
        return
    fi

    if [[ "$sub" == "tray" && $cword -eq $((subidx + 1)) && "$cur" != -* ]]; then
        COMPREPLY=( $(compgen -W "eject close lock unlock" -- "$cur") )
        return
    fi

    local opts="$global_opts"
    case "$sub" in
        tray)  opts="-i --index --bsd -j --json -h --help --version --force --persistent" ;;
        probe) opts="-i --index --bsd -j --json -h --help --version --dump" ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    fi
}
complete -F _mos mos
