# GENERATED by scripts/gen-cli-docs.py from the CLI command table (the &mos_cli_command_* array in cli/main.c, each cli/<verb>.c descriptor, cli/tray.c actions).
# Do not edit by hand: run `python3 scripts/gen-cli-docs.py` (or `make cli-docs`) and commit.
# The verb and action lists are derived, so adding a command needs no edit here.

# A subcommand has been given when one of the verbs appears in the tokens.
function __fish_mos_no_subcommand
    set -l cmd (commandline -opc)
    if test (count $cmd) -eq 1
        return 0
    end
    for word in $cmd[2..-1]
        switch $word
            case state list watch metadata drive features tray capacity probe
                return 1
        end
    end
    return 0
end

function __fish_mos_using_subcommand
    set -l cmd (commandline -opc)
    for word in $cmd[2..-1]
        switch $word
            case state list watch metadata drive features tray capacity probe
                test "$word" = "$argv[1]"
                return
        end
    end
    return 1
end

# Subcommands (only before one is chosen).
complete -c mos -f -n __fish_mos_no_subcommand -a state -d 'Report drive state (default verb)'
complete -c mos -f -n __fish_mos_no_subcommand -a list -d 'List all drives with their states'
complete -c mos -f -n __fish_mos_no_subcommand -a watch -d 'Stream state events as NDJSON until SIGINT'
complete -c mos -f -n __fish_mos_no_subcommand -a metadata -d 'Disc identity record (profile, TOC, volume)'
complete -c mos -f -n __fish_mos_no_subcommand -a drive -d 'Drive facts (identity, protection, firmware)'
complete -c mos -f -n __fish_mos_no_subcommand -a features -d 'MMC feature list with current bits'
complete -c mos -f -n __fish_mos_no_subcommand -a tray -d 'Control the tray (eject, close, lock, unlock)'
complete -c mos -f -n __fish_mos_no_subcommand -a capacity -d 'Disc capacity (media size + free/append space)'
complete -c mos -f -n __fish_mos_no_subcommand -a probe -d 'Diagnostic notification stream (mos.probe.v0)'

# tray actions (only right after `tray`).
complete -c mos -f -n '__fish_mos_using_subcommand tray' -a 'eject close lock unlock' -d 'tray action'

# Global options.
complete -c mos -s i -l index   -d '1-based drive index' -x
complete -c mos      -l bsd     -d 'BSD form selector' -x
complete -c mos -s j -l json    -d 'Emit JSON output'
complete -c mos -s h -l help    -d 'Show help'
complete -c mos      -l version -d 'Show version'

# Subcommand-scoped options.
complete -c mos -l force      -n '__fish_mos_using_subcommand tray'  -d 'eject: open no matter what (unmount + clear locks)'
complete -c mos -l persistent -n '__fish_mos_using_subcommand tray'  -d 'lock/unlock: Persistent Prevent'
complete -c mos -l dump       -n '__fish_mos_using_subcommand probe' -d 'One-shot DiscRecording capture'
