# GENERATED by scripts/gen-cli-docs.py from the CLI command table (the &mos_cli_command_* array in cli/main.c, each cli/<verb>.c descriptor, cli/tray.c actions).
# Do not edit by hand: run `python3 scripts/gen-cli-docs.py` (or `make cli-docs`) and commit.
# The verb and action lists are derived, so adding a command needs no edit here.

# Query attached optical drives from `mos list --json`. Appends BSD-node paths
# to COMPREPLY. Requires jq; no-op when absent (mos itself has no runtime deps).
_mos_drives()
{
    command -v jq >/dev/null 2>&1 || return
    local drives
    drives=$(mos list --json 2>/dev/null | jq -r '.drives[].bsd_node' 2>/dev/null)
    [[ -n "$drives" ]] && COMPREPLY+=( $(compgen -W "$drives" -- "$cur") )
}

_mos()
{
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n : || return
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

    local subcommands="state list watch metadata drive features tray capacity probe"
    local global_opts="-i --index --bsd --registry -j --json -h --help --version"

    case "$prev" in
        -i|--index|--registry) return ;;
        --bsd) _mos_drives; return ;;
    esac

    local i sub="" subidx=0
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            -*) ;;
            *) sub="${words[i]}"; subidx=$i; break ;;
        esac
    done

    if [[ -z "$sub" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
            _mos_drives
        fi
        return
    fi

    if [[ "$sub" == "tray" && $cword -eq $((subidx + 1)) && "$cur" != -* ]]; then
        COMPREPLY=( $(compgen -W "eject open close lock unlock" -- "$cur") )
        return
    fi

    local opts="$global_opts"
    case "$sub" in
        tray)
            local tray_act="" j
            for ((j=subidx+1; j < cword; j++)); do
                case "${words[j]}" in -*) ;; *) tray_act="${words[j]}"; break ;; esac
            done
            [[ -z "$tray_act" || "$tray_act" == "eject" ]] && opts="$opts --force"
            ;;
        probe) opts="$opts --dump --capture" ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    fi
}
complete -F _mos mos
